version: '3.9'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  database:
    container_name: app_postgres_dev
    image: postgres:12
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

networks:
  app-network:

volumes:
  postgres-data:
  redis:
    driver: local
