blank_issues_enabled: false
contact_links:
  - name: Product Feature Request
    url: https://github.com/cortip/isomera/discussions/17
    about: Provide feedback to the Isomera team and ask for new features or enhancements!
  - name: Documentation Bug Report
    url: https://github.com/cortip/isomera/issues/new?template=BUG_REPORT.md&title%5B%5D=BUG
    about: Create a report to help us improve the Isomera documentation.
  - name: Documentation Request
    url: https://github.com/cortip/isomera/issues/new
    about: Suggest a new part of the documentation we are missing!
  - name: Isomera Questions and Discussions
    url: https://github.com/cortip/isomera/discussions
    about: Please ask and answer questions on the community forums.
  - name: Join the Community Discord
    url: https://discord.gg/7a4uAzeYd9
    about: Come and chat with other community members!
