name: Commit E2E
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
      - run: yarn install

      - run: npx nx e2e --project dashboard-e2e --headless
#      - run: npx nx e2e --project website-e2e --headless
